import { Series } from './types';

export const seriesList: Series[] = [
  { name: '13 Reasons Why', seasons: 4 },
  { name: '24', seasons: 9 },
  { name: '3%', seasons: 4 },
  { name: '30 Rock', seasons: 7 },
  { name: 'Abbott Elementary', seasons: 3 },
  { name: 'Adventure Time', seasons: 10 },
  { name: 'Agents of S.H.I.E.L.D.', seasons: 7 },
  { name: 'Alias', seasons: 5 },
  { name: 'Alice in Borderland', seasons: 2 },
  { name: 'Altered Carbon', seasons: 2 },
  { name: 'American Dad!', seasons: 21 },
  { name: 'American Horror Story', seasons: 12 },
  { name: 'Aqua Teen Hunger Force', seasons: 12 },
  { name: 'Arcane', seasons: 1 },
  { name: 'Archer', seasons: 14 },
  { name: 'Arrested Development', seasons: 5 },
  { name: 'Ash vs Evil Dead', seasons: 3 },
  { name: 'Atlanta', seasons: 4 },
  { name: 'Attack on Titan', seasons: 4 },
  { name: 'Avatar: The Last Airbender', seasons: 3 },
  { name: 'Babylon 5', seasons: 5 },
  { name: 'Babylon Berlin', seasons: 4 },
  { name: 'Band of Brothers', seasons: 1 },
  { name: 'Barry', seasons: 4 },
  { name: 'Bates Motel', seasons: 5 },
  { name: 'Battlestar Galactica', seasons: 4 },
  { name: 'Better Call Saul', seasons: 6 },
  { name: 'Big Little Lies', seasons: 2 },
  { name: 'Billions', seasons: 7 },
  { name: 'Black Adder', seasons: 4 },
  { name: 'Black Mirror', seasons: 6 },
  { name: 'Black Sails', seasons: 4 },
  { name: 'Bluey', seasons: 3 },
  { name: 'Bob\'s Burgers', seasons: 14 },
  { name: 'BoJack Horseman', seasons: 6 },
  { name: 'Bones', seasons: 12 },
  { name: 'Borgen', seasons: 4 },
  { name: 'Bosch', seasons: 7 },
  { name: 'Boston Legal', seasons: 5 },
  { name: 'Breaking Bad', seasons: 5 },
  { name: 'Bridgerton', seasons: 3 },
  { name: 'Broadchurch', seasons: 3 },
  { name: 'Brooklyn Nine-Nine', seasons: 8 },
  { name: 'Buffy the Vampire Slayer', seasons: 7 },
  { name: 'Burn Notice', seasons: 7 },
  { name: 'Call My Agent! (Dix pour cent)', seasons: 4 },
  { name: 'Castle', seasons: 8 },
  { name: 'Castlevania', seasons: 4 },
  { name: 'Chernobyl', seasons: 1 },
  { name: 'Chuck', seasons: 5 },
  { name: 'Cidade Invisível', seasons: 2 },
  { name: 'Cobra Kai', seasons: 6 },
  { name: 'Columbo', seasons: 10 },
  { name: 'Community', seasons: 6 },
  { name: 'Cowboy Bebop', seasons: 1 },
  { name: 'Crash Landing on You', seasons: 1 },
  { name: 'Criminal Minds', seasons: 17 },
  { name: 'Curb Your Enthusiasm', seasons: 12 },
  { name: 'Daredevil', seasons: 3 },
  { name: 'Dark', seasons: 3 },
  { name: 'Dead Like Me', seasons: 2 },
  { name: 'Deadwood', seasons: 3 },
  { name: 'Death Note', seasons: 1 },
  { name: 'Derry Girls', seasons: 3 },
  { name: 'Desperate Housewives', seasons: 8 },
  { name: 'Dexter', seasons: 8 },
  { name: 'Disenchantment', seasons: 5 },
  { name: 'Doctor Who', seasons: 14 },
  { name: 'Dollhouse', seasons: 2 },
  { name: 'Downton Abbey', seasons: 6 },
  { name: 'ER', seasons: 15 },
  { name: 'Élite', seasons: 8 },
  { name: 'Entourage', seasons: 8 },
  { name: 'Euphoria', seasons: 2 },
  { name: 'Everybody Loves Raymond', seasons: 9 },
  { name: 'Family Guy', seasons: 22 },
  { name: 'Fargo', seasons: 5 },
  { name: 'Farscape', seasons: 4 },
  { name: 'Fauda', seasons: 4 },
  { name: 'Fawlty Towers', seasons: 2 },
  { name: 'Firefly', seasons: 1 },
  { name: 'Fleabag', seasons: 2 },
  { name: 'For All Mankind', seasons: 4 },
  { name: 'Foundation', seasons: 2 },
  { name: 'Frasier', seasons: 11 },
  { name: 'Friends', seasons: 10 },
  { name: 'Fringe', seasons: 5 },
  { name: 'Fullmetal Alchemist: Brotherhood', seasons: 1 },
  { name: 'Futurama', seasons: 11 },
  { name: 'Game of Thrones', seasons: 8 },
  { name: 'Gen V', seasons: 1 },
  { name: 'Gilmore Girls', seasons: 7 },
  { name: 'Glee', seasons: 6 },
  { name: 'Glow', seasons: 3 },
  { name: 'Gomorrah', seasons: 5 },
  { name: 'Gossip Girl', seasons: 6 },
  { name: 'Gravity Falls', seasons: 2 },
  { name: 'Grey\'s Anatomy', seasons: 20 },
  { name: 'Halt and Catch Fire', seasons: 4 },
  { name: 'Hannibal', seasons: 3 },
  { name: 'Happy Valley', seasons: 3 },
  { name: 'Harley Quinn', seasons: 4 },
  { name: 'Heroes', seasons: 4 },
  { name: 'His Dark Materials', seasons: 3 },
  { name: 'Historietas Assombradas (para Crianças Malcriadas)', seasons: 3 },
  { name: 'Homeland', seasons: 8 },
  { name: 'House', seasons: 8 },
  { name: 'House of Cards', seasons: 6 },
  { name: 'How I Met Your Mother', seasons: 9 },
  { name: 'How to Sell Drugs Online (Fast)', seasons: 3 },
  { name: 'I May Destroy You', seasons: 1 },
  { name: 'Invader Zim', seasons: 2 },
  { name: 'Invincible', seasons: 2 },
  { name: 'Irmão do Jorel', seasons: 5 },
  { name: 'It\'s Always Sunny in Philadelphia', seasons: 16 },
  { name: 'Justified', seasons: 6 },
  { name: 'Killing Eve', seasons: 4 },
  { name: 'Kim\'s Convenience', seasons: 5 },
  { name: 'King of the Hill', seasons: 13 },
  { name: 'Kingdom', seasons: 2 },
  { name: 'Knight Rider', seasons: 4 },
  { name: 'Letterkenny', seasons: 12 },
  { name: 'Line of Duty', seasons: 6 },
  { name: 'Loki', seasons: 2 },
  { name: 'Los Simuladores', seasons: 2 },
  { name: 'Lost', seasons: 6 },
  { name: 'Lupin', seasons: 3 },
  { name: 'Luther', seasons: 5 },
  { name: 'M*A*S*H', seasons: 11 },
  { name: 'MacGyver', seasons: 7 },
  { name: 'Mad Men', seasons: 7 },
  { name: 'Making a Murderer', seasons: 2 },
  { name: 'Malcolm in the Middle', seasons: 7 },
  { name: 'Maniac', seasons: 1 },
  { name: 'Mare of Easttown', seasons: 1 },
  { name: 'Metalocalypse', seasons: 4 },
  { name: 'Miami Vice', seasons: 5 },
  { name: 'Mindhunter', seasons: 2 },
  { name: 'Misfits', seasons: 5 },
  { name: 'Modern Family', seasons: 11 },
  { name: 'Money Heist', seasons: 5 },
  { name: 'Monk', seasons: 8 },
  { name: 'Monty Python\'s Flying Circus', seasons: 4 },
  { name: 'Mr. Bean', seasons: 1 },
  { name: 'Mr. Robot', seasons: 4 },
  { name: 'MythBusters', seasons: 20 },
  { name: 'Narcos', seasons: 3 },
  { name: 'Neon Genesis Evangelion', seasons: 1 },
  { name: 'New Girl', seasons: 7 },
  { name: 'Normal People', seasons: 1 },
  { name: 'Northern Exposure', seasons: 6 },
  { name: 'Okupas', seasons: 1 },
  { name: 'One Piece (Live Action)', seasons: 1 },
  { name: 'One-Punch Man', seasons: 2 },
  { name: 'Only Murders in the Building', seasons: 4 },
  { name: 'Orange Is the New Black', seasons: 7 },
  { name: 'Orphan Black', seasons: 5 },
  { name: 'Our Flag Means Death', seasons: 2 },
  { name: 'Outlander', seasons: 7 },
  { name: 'Ozark', seasons: 4 },
  { name: 'Parks and Recreation', seasons: 7 },
  { name: 'Peaky Blinders', seasons: 6 },
  { name: 'Peep Show', seasons: 9 },
  { name: 'Penny Dreadful', seasons: 3 },
  { name: 'Person of Interest', seasons: 5 },
  { name: 'Planet Earth', seasons: 2 },
  { name: 'Pose', seasons: 3 },
  { name: 'Preacher', seasons: 4 },
  { name: 'Pretty Little Liars', seasons: 7 },
  { name: 'Prison Break', seasons: 5 },
  { name: 'Psych', seasons: 8 },
  { name: 'Pushing Daisies', seasons: 2 },
  { name: 'Quantum Leap', seasons: 5 },
  { name: 'Queer Eye', seasons: 8 },
  { name: 'Reacher', seasons: 2 },
  { name: 'Reno 911!', seasons: 8 },
  { name: 'Reservation Dogs', seasons: 3 },
  { name: 'Rick and Morty', seasons: 7 },
  { name: 'Rome', seasons: 2 },
  { name: 'Russian Doll', seasons: 2 },
  { name: 'Sacred Games', seasons: 2 },
  { name: 'Samurai Jack', seasons: 5 },
  { name: 'Santa Clarita Diet', seasons: 3 },
  { name: 'Scandal', seasons: 7 },
  { name: 'Schitt\'s Creek', seasons: 6 },
  { name: 'Scooby-Doo, Where Are You!', seasons: 2 },
  { name: 'Scrubs', seasons: 9 },
  { name: 'Seinfeld', seasons: 9 },
  { name: 'Sense8', seasons: 2 },
  { name: 'Severance', seasons: 1 },
  { name: 'Sex and the City', seasons: 6 },
  { name: 'Sex Education', seasons: 4 },
  { name: 'Shameless (US)', seasons: 11 },
  { name: 'Sherlock', seasons: 4 },
  { name: 'Shtisel', seasons: 3 },
  { name: 'Silicon Valley', seasons: 6 },
  { name: 'Six Feet Under', seasons: 5 },
  { name: 'Skam', seasons: 4 },
  { name: 'Skins (UK)', seasons: 7 },
  { name: 'Smallville', seasons: 10 },
  { name: 'Smiling Friends', seasons: 2 },
  { name: 'Snowfall', seasons: 6 },
  { name: 'Sons of Anarchy', seasons: 7 },
  { name: 'South Park', seasons: 26 },
  { name: 'Spartacus', seasons: 4 },
  { name: 'SpongeBob SquarePants', seasons: 15 },
  { name: 'Squid Game', seasons: 1 },
  { name: 'Star Trek: Deep Space Nine', seasons: 7 },
  { name: 'Star Trek: Discovery', seasons: 5 },
  { name: 'Star Trek: Enterprise', seasons: 4 },
  { name: 'Star Trek: Lower Decks', seasons: 4 },
  { name: 'Star Trek: Picard', seasons: 3 },
  { name: 'Star Trek: Prodigy', seasons: 1 },
  { name: 'Star Trek: Strange New Worlds', seasons: 2 },
  { name: 'Star Trek: The Next Generation', seasons: 7 },
  { name: 'Star Trek: Voyager', seasons: 7 },
  { name: 'Stargate Atlantis', seasons: 5 },
  { name: 'Stargate SG-1', seasons: 10 },
  { name: 'Stargate Universe', seasons: 2 },
  { name: 'Stranger Things', seasons: 4 },
  { name: 'Succession', seasons: 4 },
  { name: 'Suits', seasons: 9 },
  { name: 'Supernatural', seasons: 15 },
  { name: 'Taskmaster', seasons: 17 },
  { name: 'Ted Lasso', seasons: 3 },
  { name: 'Teen Titans', seasons: 5 },
  { name: 'Teen Wolf', seasons: 6 },
  { name: 'That \'70s Show', seasons: 8 },
  { name: 'The 100', seasons: 7 },
  { name: 'The A-Team', seasons: 5 },
  { name: 'The Addams Family', seasons: 2 },
  { name: 'The Americans', seasons: 6 },
  { name: 'The Bear', seasons: 2 },
  { name: 'The Big Bang Theory', seasons: 12 },
  { name: 'The Blacklist', seasons: 10 },
  { name: 'The Boys', seasons: 4 },
  { name: 'The Clone Wars', seasons: 7 },
  { name: 'The Crown', seasons: 6 },
  { name: 'The Expanse', seasons: 6 },
  { name: 'The Falcon and the Winter Soldier', seasons: 1 },
  { name: 'The Fresh Prince of Bel-Air', seasons: 6 },
  { name: 'The Good Doctor', seasons: 7 },
  { name: 'The Good Place', seasons: 4 },
  { name: 'The Great', seasons: 3 },
  { name: 'The Handmaid\'s Tale', seasons: 5 },
  { name: 'The Haunting of Hill House', seasons: 1 },
  { name: 'The House of Flowers (La Casa de las Flores)', seasons: 3 },
  { name: 'The Inbetweeners', seasons: 3 },
  { name: 'The IT Crowd', seasons: 4 },
  { name: 'The Killing (Forbrydelsen)', seasons: 3 },
  { name: 'The King of Queens', seasons: 9 },
  { name: 'The Last Dance', seasons: 1 },
  { name: 'The Last of Us', seasons: 1 },
  { name: 'The League', seasons: 7 },
  { name: 'The Leftovers', seasons: 3 },
  { name: 'The Legend of Korra', seasons: 4 },
  { name: 'The Magicians', seasons: 5 },
  { name: 'The Man in the High Castle', seasons: 4 },
  { name: 'The Mandalorian', seasons: 3 },
  { name: 'The Marvelous Mrs. Maisel', seasons: 5 },
  { name: 'The Mentalist', seasons: 7 },
  { name: 'The Mindy Project', seasons: 6 },
  { name: 'The Munsters', seasons: 2 },
  { name: 'The Night Of', seasons: 1 },
  { name: 'The OC', seasons: 4 },
  { name: 'The Office (US)', seasons: 9 },
  { name: 'The Orville', seasons: 3 },
  { name: 'The Outer Limits', seasons: 7 },
  { name: 'The Punisher', seasons: 2 },
  { name: 'The Queen\'s Gambit', seasons: 1 },
  { name: 'The Righteous Gemstones', seasons: 3 },
  { name: 'The Shield', seasons: 7 },
  { name: 'The Simpsons', seasons: 36 },
  { name: 'The Sopranos', seasons: 6 },
  { name: 'The Tudors', seasons: 4 },
  { name: 'The Twilight Zone', seasons: 5 },
  { name: 'The Umbrella Academy', seasons: 4 },
  { name: 'The Vampire Diaries', seasons: 8 },
  { name: 'The Venture Bros.', seasons: 7 },
  { name: 'The Walking Dead', seasons: 11 },
  { name: 'The West Wing', seasons: 7 },
  { name: 'The White Lotus', seasons: 2 },
  { name: 'The Wire', seasons: 5 },
  { name: 'The Witcher', seasons: 3 },
  { name: 'The X-Files', seasons: 11 },
  { name: 'This Is Us', seasons: 6 },
  { name: 'Tiger King', seasons: 2 },
  { name: 'Top Boy', seasons: 5 },
  { name: 'Top Gear (UK)', seasons: 33 },
  { name: 'Torchwood', seasons: 4 },
  { name: 'True Blood', seasons: 7 },
  { name: 'True Detective', seasons: 4 },
  { name: 'Twin Peaks', seasons: 3 },
  { name: 'Two and a Half Men', seasons: 12 },
  { name: 'Ugly Betty', seasons: 4 },
  { name: 'Unbreakable Kimmy Schmidt', seasons: 4 },
  { name: 'Veep', seasons: 7 },
  { name: 'Veronica Mars', seasons: 4 },
  { name: 'Vikings', seasons: 6 },
  { name: 'WandaVision', seasons: 1 },
  { name: 'Watchmen', seasons: 1 },
  { name: 'Wednesday', seasons: 1 },
  { name: 'Weeds', seasons: 8 },
  { name: 'Wentworth', seasons: 9 },
  { name: 'Westworld', seasons: 4 },
  { name: 'What We Do in the Shadows', seasons: 5 },
  { name: 'White Collar', seasons: 6 },
  { name: 'Wilfred', seasons: 4 },
  { name: 'Xena: Warrior Princess', seasons: 6 },
  { name: 'Yellowjackets', seasons: 2 },
  { name: 'Yellowstone', seasons: 5 },
  { name: 'You', seasons: 5 },
];